openapi: 3.0.3
info:
  title: Monitoring Events (Internal)
  version: 1.0.0
  description: 內部監控事件結構，用於定義輸出訊息的欄位與允許值。
servers:
  - url: http://localhost
paths:
  /monitoring/events:
    post:
      summary: 送出一筆監控事件
      description: 僅作為內部事件契約，實際輸出為 bot 端單行提示。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonitoringEvent'
      responses:
        '204':
          description: 事件已接收（無內容回應）
components:
  schemas:
    MonitoringEvent:
      type: object
      required:
        - type
        - timestamp
        - summary
      properties:
        type:
          type: string
          enum: [startup, received, replied, error, heartbeat]
        timestamp:
          type: string
          description: 事件發生時間（本地時間字串）
        summary:
          type: string
          description: 單行摘要（不得含敏感資料）
        suppressed_count:
          type: integer
          minimum: 0
          description: 同類錯誤被抑制的次數
