openapi: 3.0.3
info:
  title: 個人助理回覆與記憶檢索 API
  version: 1.0.0
  description: 用於「接收訊息 → 回覆」與「記憶檢索」的介面契約
paths:
  /assistant/reply:
    post:
      summary: 取得助理回覆
      description: 接收使用者訊息，回傳直接回覆或工具調用後的回覆內容
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReplyRequest'
      responses:
        '200':
          description: 回覆成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReplyResponse'
  /assistant/memory/search:
    post:
      summary: 記憶檢索
      description: 以語意查詢在地記憶並回傳相關結果
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemorySearchRequest'
      responses:
        '200':
          description: 檢索成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemorySearchResponse'
components:
  schemas:
    ReplyRequest:
      type: object
      required:
        - user_id
        - chat_id
        - content
      properties:
        user_id:
          type: string
          description: 使用者識別
        chat_id:
          type: string
          description: Telegram 對話識別
        content:
          type: string
          description: 使用者訊息內容
    ReplyResponse:
      type: object
      required:
        - reply
        - decision
      properties:
        reply:
          type: string
          description: 助理回覆內容
        decision:
          type: string
          description: 回覆決策
          enum: [direct_reply, use_tool]
        memory_saved:
          type: boolean
          description: 是否新增記憶
        memory_hits:
          type: array
          description: 記憶命中摘要（如適用）
          items:
            type: string
    MemorySearchRequest:
      type: object
      required:
        - user_id
        - query
      properties:
        user_id:
          type: string
          description: 使用者識別
        query:
          type: string
          description: 查詢字串
        top_k:
          type: integer
          description: 回傳筆數
          default: 5
    MemorySearchResponse:
      type: object
      required:
        - results
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/MemorySearchItem'
    MemorySearchItem:
      type: object
      required:
        - content
        - score
      properties:
        content:
          type: string
          description: 命中內容
        score:
          type: number
          description: 相似度分數
